name: "Build: Sample"

on:
  push:
    branches:
      - main
    paths:
      - src
      - gradle
      - build.gradle.kts
      - gradle.properties
      - settings.gradle.kts
      - .github/workflows/build.ci.yml

  pull_request:
    paths:
      - src
      - gradle
      - build.gradle.kts
      - gradle.properties
      - settings.gradle.kts
      - .github/workflows/build.ci.yml

jobs:
  ## Build sample app
  build-sample:
    name: "Build: Sample"
    uses: elide-dev/build-infra/.github/workflows/jvm.gradle.yml@main
    with:
      action: 'build'
