name: "Build: Sample"

on:
  push:
    branches:
      - main
    paths:
      - "*.kt"
      - "*.kts"
      - gradle
      - build.gradle.kts
      - gradle.properties
      - settings.gradle.kts
      - .github/workflows/build.ci.yml

  pull_request:
    paths:
      - "*.kt"
      - "*.kts"
      - gradle
      - build.gradle.kts
      - gradle.properties
      - settings.gradle.kts
      - .github/workflows/build.ci.yml

  schedule:
    - cron: '30 */2 * * *'

jobs:
  ## Build sample app
  build-sample:
    name: "Sample App"
    uses: elide-dev/build-infra/.github/workflows/jvm.gradle.yml@ceb5db9cdbb8af843f7d91e1aea973cebe17f575
    secrets:
      BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    permissions:
      checks: write
      pull-requests: read
      id-token: write
      actions: read
      contents: write
    with:
      jvm: '19'
      runner: ubuntu-latest
      flags: '--scan --stacktrace'
